### ISSUE TITLE
RM3 mini: response to auth is only 56 bytes

### ISSUE THREAD

**Issue by chemelli74** [PainElemental/BroadlinkControl#1]
Hi,

I receive a 56 bytes response to my 0x065 auth packet. As the protocol says to skip first 0x38 bytes, I get an empty array.

Any idea ?
Thx,

Simone

**Comment by PainElemental** [comment]
Sorry, but I don't know. IR works fine for me, just RF does not work using this tool.

Regards

**Comment by chemelli74** [comment]
Protocol fixed in another library implementation.

Simone
